### ISSUE TITLE
Missing edges in ea_dict causes templates to fail

### ISSUE THREAD

**Issue by KunhuanLiu** [tobacco-mofs/tobacco_3.0#13]
There are several topologies like **ece.cif** which includes 8 edges per vertex, but after calling `assign_node_vecs2edges()` only 7 edges are stored for each node. This causes "Key error" when `SBU_coords()` try to fetch the 8th edge vector from `ea_dict()`. It seems to be related to the algorithm for building `asd`, but I don't know how it causes this problem only for certain topologies.

Example error traceback:
```
	Traceback (most recent call last):
	  File "tobacco.py", line 345, in run_template
	    all_SBU_coords = SBU_coords(TG, ea_dict, CONNECTION_SITE_BOND_LENGTH)
	  File "folder/SBU_geometry.py", line 33, in SBU_coords
	    xvecname,dx_v,xvec = ea_dict[vertex][ind]
KeyError: 6
```

**Comment by rytheranderson** [comment]
This is something I have been aware of for awhile, I have found it to happen only if the building block geometry matches the vertex geometry very poorly. That being said, this is not desirable behavior, I will look more deeply into the issue and see if the error can be stopped or at least replaced with a warning.

**Comment by KunhuanLiu** [comment]
It looks to me that some edges are not recognized during the "analysis" of the template (like storing the edge info for node). The templates I pointed out usually have several edges that connect the same id of vertices (for example, V1--Er2, but also V1--Er2[the other cell]).

**Comment by rytheranderson** [comment]
So I looked deeply into this today, it seems ToBaCCo is reading the ece template correctly, and it should read all other templates correctly even if two vertices are connected by multiple edges. One instance where the template reading may fail is if a template only has one node. 

What was happening with the ece template was the nodular building block vectors (pointing from the node building block center of mass to each connection point) were being assigned multiple edges, which should not happen. This could only happen if the net-vertex/building block geometries match poorly, as is the case for ece and all the 8-connected building blocks I currently have. This is because edges were assigned to building block vectors by superimposing the vectors onto a vertex and assigning each vector the edge that it was closest to after superimposition. Thus, if two building block vectors were both closest to the same edge they would both be assigned this edge, leaving one edge unassigned and resulting in the key error later when that edge is looked up in the assignment dictionary. 

I have adjusted the algorithm so that all the building block vector to edge distances are calculated first, then the shortest distance is assigned, followed by the next shortest etc., while excluding any distances in which the edge has already been assigned. This algorithm will yield the "best" (lowest sum of distances) assignment even in cases of poor matching, and will ensure all building block vectors are assigned an edge. 

In some cases, poor matching may be fixed by scaling, however, for ece the output cif has a bond check, meaning the default bonding algorithm did not work (a sign of bad geometry matching). Generally, I exclude all structures with a bond check. I have also added an error message that warns the user when the edge assignment has large deviations.

I am closing this issue for now, let me know if you encounter a similar error, especially for template/node pairs where the geometry matches well (as this would likely be from an error reading the template).
